name: Studio Auslastung

on:
  schedule:
    - cron: "/5 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Abhängigkeiten installieren
        run: pip install -r requirements.txt

      - name: Skript ausführen
        run: python scrape.py

      - name: Daten speichern
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          # Änderungen sichern
          git stash push -m "before pull" --include-untracked

          # Remote holen
          git pull --rebase origin main

          # Änderungen zurückholen
          git stash pop

          # commit & push
          git add werte.csv
          git commit -m "Neue Studioauslastung" || echo "Keine Änderungen"
          git push
